---
title: "ML Urban Analysis Project"
author: "Drew Duffy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
```

# Data for Boston
  - Last Marathon Date: April 15, 2024

```{r Boston}

# zip("allboston_rds.zip", "all_boston.rds")



all_boston <- readRDS("all_boston.rds")

# calendar 
# boscalendar <- read.csv("C://Users/Drew Duffy/Downloads/bostonmarathon_calendar.csv.gz")
# 
# boscalendar_clean <- boscalendar %>% 
#   mutate(date = as.Date(date, format = "%Y-%m-%d"), 
#          available = ifelse(available == "t", 1, 0), 
#          price = as.numeric(gsub("[^0-9.]", "", price))) 
# 
# # listings 
# boslistings <- read.csv("C://Users/Drew Duffy/Downloads/listings (2).csv.gz") %>% 
#   rename(listing_id = id) %>% 
#   select(-price, -maximum_nights, -minimum_nights)
# 
# 
# all_boston <- merge(boscalendar_clean, boslistings, by = "listing_id")

# all_boston <- all_boston %>%
#   select(
#     listing_id, date, available, price, minimum_nights, maximum_nights, listing_url,
#     name, description, neighborhood_overview, picture_url, host_id, host_url,
#     host_name, host_since, host_location, host_about, host_response_time,
#     host_response_rate, host_neighbourhood, host_listings_count,
#     host_total_listings_count, neighbourhood, neighbourhood_cleansed,
#     neighbourhood_group_cleansed, latitude, longitude, property_type, room_type,
#     accommodates, bathrooms, bathrooms_text, bedrooms, beds, amenities,
#     minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights,
#     maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm,
#     has_availability, availability_30, availability_60, availability_90,
#     availability_365, number_of_reviews, review_scores_rating,
#     review_scores_accuracy, review_scores_cleanliness, review_scores_checkin,
#     review_scores_communication, review_scores_location, review_scores_value,
#     reviews_per_month, marathon_week
#   )

# all_boston <- all_boston %>% 
#   mutate(marathon_week = if_else(date >= ymd("2024-04-11") & date <= ymd("2024-04-18"), 1, 0))

saveRDS(all_boston, "all_boston.rds")

#zip("allboston_rds.zip", "all_boston.rds")


```

# Data for New York
 - Last Marathon Date: November 3, 2024

```{r New York}

all_ny <- readRDS("all_ny.rds")

# calendar 

# nycalendar <- read.csv("C://Users/Drew Duffy/Downloads/nycalendar_try.csv.gz")
# 
# nycalendar_clean <- nycalendar %>%
#    mutate(date = as.Date(date, format = "%Y-%m-%d"),
#           available = ifelse(available == "t", 1, 0),
#            price = as.numeric(gsub("[^0-9.]", "", price)))
#  #
# # # # listings
# nylistings <- read.csv("C://Users/Drew Duffy/Downloads/nylistings_try.csv.gz") %>%
#   rename(listing_id = id) %>%
#   select(-price, -maximum_nights, -minimum_nights)
# # 
# all_ny <- merge(nycalendar_clean, nylistings, by = "listing_id")
# 
# all_ny_filter <- all_ny %>% 
#   mutate(year = year(date)) %>% 
#   filter(year == 2024, price >0) %>% 
#   select(-license, -calculated_host_listings_count_shared_rooms, -calculated_host_listings_count_private_rooms, -calculated_host_listings_count_entire_homes, -neighborhood_overview, -host_about, -host_url, -host_response_time, -host_response_rate, -host_acceptance_rate, -host_is_superhost, -host_thumbnail_url, -host_picture_url, -adjusted_price, -calendar_updated, -calendar_last_scraped)

# 
# all_ny <- all_ny %>% 
#   mutate(marathon_week = if_else(date >= ymd("2024-10-30") & date <= ymd("2024-11-06"), 1, 0))
#   
#   
# all_ny <- all_ny %>%
#   select(
#     listing_id, date, available, price, minimum_nights, maximum_nights, listing_url,
#     name, description, picture_url, host_id,
#     host_name, host_since, host_location, host_neighbourhood, host_listings_count,
#     host_total_listings_count, neighbourhood, neighbourhood_cleansed,
#     neighbourhood_group_cleansed, latitude, longitude, property_type, room_type,
#     accommodates, bathrooms, bathrooms_text, bedrooms, beds, amenities,
#     minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights,
#     maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm,
#     has_availability, availability_30, availability_60, availability_90,
#     availability_365, number_of_reviews, review_scores_rating,
#     review_scores_accuracy, review_scores_cleanliness, review_scores_checkin,
#     review_scores_communication, review_scores_location, review_scores_value,
#     reviews_per_month, marathon_week
#   )

saveRDS(all_ny, "all_ny.rds")

#zip("allny_rds.zip", "all_ny.rds")

```
# Data for Chicago
  - Last Marathon Date: October 13, 2024

```{r Chicago}

all_chicago <- readRDS("all_chicago.rds")

# # calendar 
# chicalendar <- read.csv("C://Users/Drew Duffy/Downloads/chicagomarathon_calendar.csv.gz")
# # 
# chicalendar_clean <- chicalendar %>% 
#   mutate(date = as.Date(date, format = "%Y-%m-%d"), 
#          available = ifelse(available == "t", 1, 0), 
#           price = as.numeric(gsub("[^0-9.]", "", price))) 
#  
# # listings 
# chilistings <- read.csv("C://Users/Drew Duffy/Downloads/chicagomarathon_listings.csv.gz") %>% 
#   rename(listing_id = id) %>% 
#   select(-price, -maximum_nights, -minimum_nights)
# # 
# all_chicago <- merge(chicalendar_clean, chilistings, by = "listing_id")


# all_chicago <- all_chicago %>%
#   mutate(marathon_week = if_else(date >= ymd("2024-10-09") & date <= ymd("2024-10-16"), 1, 0))
# 
# 
# all_chicago <- all_chicago %>%
#   select(
#     listing_id, date, available, price, minimum_nights, maximum_nights, listing_url,
#     name, description, picture_url, host_id,
#     host_name, host_since, host_location, host_neighbourhood, host_listings_count,
#     host_total_listings_count, neighbourhood, neighbourhood_cleansed,
#     neighbourhood_group_cleansed, latitude, longitude, property_type, room_type,
#     accommodates, bathrooms, bathrooms_text, bedrooms, beds, amenities,
#     minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights,
#     maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm,
#     has_availability, availability_30, availability_60, availability_90,
#     availability_365, number_of_reviews, review_scores_rating,
#     review_scores_accuracy, review_scores_cleanliness, review_scores_checkin,
#     review_scores_communication, review_scores_location, review_scores_value,
#     reviews_per_month, marathon_week
#   )
# # 
# saveRDS(all_chicago, "all_chicago.rds")

# zip("allchicago_rds.zip", "all_chicago.rds")

```

# Data for San Francisco
  - Last Marathon Date: July 28, 2024

```{r San Fran}

all_sf <- readRDS("all_sf.rds")

# calendar 
# sfcalendar <- read.csv("C://Users/Drew Duffy/Downloads/sfmarathon_calendar.csv.gz")
# # 
# sfcalendar_clean <- sfcalendar %>% 
#   mutate(date = as.Date(date, format = "%Y-%m-%d"), 
#          available = ifelse(available == "t", 1, 0), 
#           price = as.numeric(gsub("[^0-9.]", "", price))) 
#  
# # listings 
# sflistings <- read.csv("C://Users/Drew Duffy/Downloads/sfmarathon_listings.csv.gz") %>% 
#   rename(listing_id = id) %>% 
#   select(-price, -maximum_nights, -minimum_nights)
# # 
# all_sf <- merge(sfcalendar_clean, sflistings, by = "listing_id")

#  all_sf <- all_sf %>%
#    mutate(marathon_week = if_else(date >= ymd("2024-07-24") & date <= ymd("2024-07-31"), 1, 0))
# # 
# # 
# all_sf <- all_sf %>%
#   select(
#     listing_id, date, available, price, minimum_nights, maximum_nights, listing_url,
#     name, description, picture_url, host_id,
#     host_name, host_since, host_location, host_neighbourhood, host_listings_count,
#     host_total_listings_count, neighbourhood, neighbourhood_cleansed,
#     neighbourhood_group_cleansed, latitude, longitude, property_type, room_type,
#     accommodates, bathrooms, bathrooms_text, bedrooms, beds, amenities,
#     minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights,
#     maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm,
#     has_availability, availability_30, availability_60, availability_90,
#     availability_365, number_of_reviews, review_scores_rating,
#     review_scores_accuracy, review_scores_cleanliness, review_scores_checkin,
#     review_scores_communication, review_scores_location, review_scores_value,
#     reviews_per_month, marathon_week
#   )






# 
 # saveRDS(all_sf, "all_sf.rds")

# zip("allsf_rds.zip", "all_sf.rds")


```


# Data for Denver
  - Last Marathon Date: May 19, 2024

```{r Denver}
all_denver <- readRDS("all_denver.rds")
# calendar 
# dencalendar <- read.csv("C://Users/Drew Duffy/Downloads/denvermarathon_calendar.csv.gz")
# # 
# dencalendar_clean <- dencalendar %>% 
#   mutate(date = as.Date(date, format = "%Y-%m-%d"), 
#          available = ifelse(available == "t", 1, 0), 
#           price = as.numeric(gsub("[^0-9.]", "", price))) 
#  
# # listings 
# denlistings <- read.csv("C://Users/Drew Duffy/Downloads/denvermarathon_listings.csv.gz") %>% 
#   rename(listing_id = id) %>% 
#   select(-price, -maximum_nights, -minimum_nights)
# # 
# all_denver <- merge(dencalendar_clean, denlistings, by = "listing_id")

#  all_denver <- all_denver %>%
#    mutate(marathon_week = if_else(date >= ymd("2024-05-15") & date <= ymd("2024-05-22"), 1, 0))
# # # 
# # # 
# all_denver <- all_denver %>%
#   select(
#     listing_id, date, available, price, minimum_nights, maximum_nights, listing_url,
#     name, description, picture_url, host_id,
#     host_name, host_since, host_location, host_neighbourhood, host_listings_count,
#     host_total_listings_count, neighbourhood, neighbourhood_cleansed,
#     neighbourhood_group_cleansed, latitude, longitude, property_type, room_type,
#     accommodates, bathrooms, bathrooms_text, bedrooms, beds, amenities,
#     minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights,
#     maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm,
#     has_availability, availability_30, availability_60, availability_90,
#     availability_365, number_of_reviews, review_scores_rating,
#     review_scores_accuracy, review_scores_cleanliness, review_scores_checkin,
#     review_scores_communication, review_scores_location, review_scores_value,
#     reviews_per_month, marathon_week
#   )

# 
# saveRDS(all_denver, "all_denver.rds")

# zip("alldenver_rds.zip", "all_denver.rds")

```